# Generated by Django 5.0 on 2023-12-07 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='homepost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postname', models.CharField(max_length=20, verbose_name='Name')),
                ('introduction', models.TextField(max_length=500, verbose_name='Introduction')),
                ('writer', models.CharField(max_length=20, null=True, verbose_name='writer')),
                ('website', models.URLField(blank=True, max_length=250, null=True)),
                ('post_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('tags', models.ManyToManyField(blank=True, to='Blog.tag')),
            ],
        ),
    ]
