# Generated by Django 5.0 on 2023-12-08 13:58

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_archives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepost',
            name='introduction',
            field=mdeditor.fields.MDTextField(max_length=500, verbose_name='Introduction'),
        ),
    ]
