# Generated by Django 5.0 on 2023-12-08 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='archive',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.archives'),
        ),
    ]
