# Generated by Django 5.0 on 2023-12-08 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_content_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='archive',
        ),
        migrations.AddField(
            model_name='archives',
            name='content',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.content'),
        ),
    ]
