# Generated by Django 5.0 on 2023-12-09 13:26

import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_remove_content_archive_archives_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='introduction',
            field=mdeditor.fields.MDTextField(max_length=10000, verbose_name='Introduction'),
        ),
    ]
