# Generated by Django 5.0 on 2023-12-12 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_content1_repository'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='content',
            new_name='archives_content',
        ),
        migrations.RenameModel(
            old_name='content1',
            new_name='repository_content',
        ),
        migrations.RenameField(
            model_name='archives',
            old_name='content',
            new_name='archives_content',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='content1',
        ),
        migrations.AddField(
            model_name='repository',
            name='repository_content',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.repository_content'),
        ),
    ]
