# Generated by Django 5.0 on 2023-12-12 01:31

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_rename_content_archives_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archives_content',
            name='introduction',
            field=mdeditor.fields.MDTextField(blank=True, max_length=10000, verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='repository_content',
            name='introduction',
            field=mdeditor.fields.MDTextField(blank=True, max_length=10000, verbose_name='Introduction'),
        ),
    ]
