# Generated by Django 5.0 on 2024-01-01 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_repository_content_ppt_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository_content',
            old_name='ppt_file',
            new_name='file',
        ),
    ]
